### ISSUE TITLE
PrintCluster  这个方法不存在

### ISSUE THREAD

**Issue by tiantangniao** [szlhl1040/Vehicles-Dispatch-Simulator#1]
请问这个方法可以提供下么，具体使用来干什么的，只是打印一下么

**Comment by szlhl1040** [comment]
不好意思，这个方法的命名错误了现在改为了DrawOneCluster，用途是生成cluster和添加邻居cluster的时候进行可视化展示和检查用的，不会影响到模拟运行的结果，我已经将新版代码提交了，谢谢。下面是此方法展示用例。
![image](https://user-images.githubusercontent.com/32859515/103271734-00d9fa80-49f6-11eb-8db9-e557c36d58f6.png)

**Comment by tiantangniao** [comment]
谢谢
