### ISSUE TITLE
Path 是路径吗

### ISSUE THREAD

**Issue by tiantangniao** [szlhl1040/Vehicles-Dispatch-Simulator#2]
这个有深入做下去的计划么

**Comment by szlhl1040** [comment]
不好意思，这个是之前做的时候的遗留，重构的时候没有清理干净，原本是通过递归查找路径来计算耗费时间，这里我们提供的地图是已经预先计算好的点对点的路程耗费了，省去了大量计算时间，我已经提交了改正后的版本，谢谢。
