### ISSUE TITLE
路网处理疑问

### ISSUE THREAD

**Issue by Clown1206** [szlhl1040/Vehicles-Dispatch-Simulator#6]
前辈您好，请问您根据实际路网划分区域的时候，是怎样处理桥梁和非桥梁道路之间的连接关系的？

**Comment by szlhl1040** [comment]
只计算路的开始和结束端，可以通过开始和结束端确定连接的邻居路段，因此可以不用特殊处理桥梁等路段，因为真实场景下桥上的汽车也必须开到下一个道路端点交界处进入别的路段，而不会从桥上飞到桥下的路上
